#!/usr/bin/env python3
"""
Script to extract room data from the mazewebsite HTML files
and generate JavaScript roomData object.

Usage:
    python extract_room_data.py

Make sure this script is in the same directory as the 'mazewebsite' folder.
"""

import re
import glob
import os
from html.parser import HTMLParser

class RoomHTMLParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.in_body = False
        self.text_content = []
        self.current_text = ''
        self.skip_tags = {'map', 'img', 'a', 'script', 'style'}
        self.current_tag = None
        
    def handle_starttag(self, tag, attrs):
        if tag == 'body':
            self.in_body = True
        if tag in self.skip_tags:
            self.current_tag = tag
            
    def handle_endtag(self, tag):
        if tag in self.skip_tags:
            self.current_tag = None
    
    def handle_data(self, data):
        if self.in_body and self.current_tag not in self.skip_tags:
            stripped = data.strip()
            if stripped and not stripped.startswith('Note:') and 'Home' not in stripped:
                self.text_content.append(stripped)

def extract_room_data(html_file):
    """Extract room data from an HTML file."""
    with open(html_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Extract room number
    room_match = re.search(r'room(\d+)\.html', html_file)
    if not room_match:
        return None
    room_num = int(room_match.group(1))
    
    # Extract title
    title_match = re.search(r'<title>(.*?)</title>', content, re.IGNORECASE)
    title = title_match.group(1) if title_match else f"Room {room_num}"
    
    # Extract text content
    parser = RoomHTMLParser()
    parser.feed(content)
    text = '\n\n'.join(parser.text_content)
    
    # Extract image map coordinates and doors
    areas = re.findall(r'<area[^>]*coords="([^"]*)"[^>]*href="room(\d+)\.html"', content, re.IGNORECASE)
    
    doors = sorted([int(door) for coords, door in areas])
    clickable_areas = []
    
    for coords, door in areas:
        coord_list = [int(x.strip()) for x in coords.split(',')]
        clickable_areas.append({
            'door': int(door),
            'coords': coord_list
        })
    
    return {
        'room_num': room_num,
        'title': title,
        'text': text,
        'doors': doors,
        'clickable_areas': clickable_areas
    }

def generate_javascript_object(rooms_data):
    """Generate JavaScript roomData object."""
    js_output = "const roomData = {\n"
    
    for room in sorted(rooms_data, key=lambda x: x['room_num']):
        js_output += f"    {room['room_num']}: {{\n"
        js_output += f"        title: \"{room['title']}\",\n"
        
        # Escape text for JavaScript
        text_escaped = room['text'].replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n\\\n')
        js_output += f"        text: `{room['text']}`,\n"
        
        js_output += f"        image: '../images/room{room['room_num']}.jpg',\n"
        js_output += f"        doors: [{', '.join(map(str, room['doors']))}],\n"
        js_output += f"        clickableAreas: [\n"
        
        for area in room['clickable_areas']:
            coords_str = ', '.join(map(str, area['coords']))
            js_output += f"            {{ door: {area['door']}, coords: [{coords_str}] }},\n"
        
        js_output += f"        ]\n"
        js_output += f"    }},\n\n"
    
    js_output += "};\n"
    return js_output

def main():
    # Find all room HTML files
    maze_dir = './'
    if not os.path.exists(maze_dir):
        print(f"Error: '{maze_dir}' directory not found!")
        print("Make sure this script is in the same directory as the 'mazewebsite' folder.")
        return
    
    html_files = glob.glob(os.path.join(maze_dir, 'room*.html'))
    
    if not html_files:
        print(f"Error: No room*.html files found in '{maze_dir}' directory!")
        return
    
    print(f"Found {len(html_files)} room files. Extracting data...")
    
    rooms_data = []
    for html_file in sorted(html_files):
        room_data = extract_room_data(html_file)
        if room_data:
            rooms_data.append(room_data)
            print(f"  Extracted Room {room_data['room_num']}")
    
    print(f"\nGenerating JavaScript output...")
    
    # Generate JavaScript object
    js_output = generate_javascript_object(rooms_data)
    
    # Save to file
    output_file = 'roomData_extracted.js'
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("// Auto-generated room data from maze HTML files\n")
        f.write("// Generated by extract_room_data.py\n\n")
        f.write(js_output)
    
    print(f"\n✓ Successfully generated '{output_file}'")
    print(f"✓ Extracted data for {len(rooms_data)} rooms")
    print(f"\nNext steps:")
    print(f"1. Review the generated '{output_file}' file")
    print(f"2. Copy the roomData object into your app.js file")
    print(f"3. Replace the existing roomData with the new one")

if __name__ == '__main__':
    main()